server:
  port: 8081
  servlet:
    context-path: /xinyang


spring:
  # 设置数据库的访问信息
  #datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3308/coldchain?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    #password: liyoujing
    #username: root
    #name: coldchain
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://222.73.159.77:1433;databaseName=tmstest
    username: sa
    password: Lm408083431

  #thymeleaf:
    #prefix: classpath:/templates/
    #suffix: .html

  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.SQLServer2008Dialect

  mvc:
    view:
      # 设置视图的默认位置在module目录下
      prefix: /module/
      suffix: .html

  #redis:
    #database: 0  #Redis数据库索引（默认为0）
    #host: localhost # redis服务器地址
    #port: 6379  #redis端口号

  mybatis:
    mapper-locations: classpath:mapper/*Mapper.xml
    type-aliases-package: com.xinya.coldchain.*.model
    configuration:
      mapUnderscoreToCamelCase: true

logging:
  config: classpath:logback-springboot.xml





