server:
  port: 8081
  servlet:
    context-path: /xinyang


spring:
  # 设置数据库的访问信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/coldchain?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    password: liyoujing
    username: root
    name: coldchain

  mvc:
    view:
      # 设置视图的默认位置在module目录下
      prefix: /module/
  redis:
    database: 0  #Redis数据库索引（默认为0）
    host: localhost # redis服务器地址
    port: 6379  #redis端口号




